# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
