# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181108_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='slug',
        ),
        migrations.AddField(
            model_name='payment',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Pool'),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Pool'),
        ),
    ]
